### ISSUE TITLE
Docker file not activate

### ISSUE THREAD

**Issue by BrainTeaserSem** [codalab/codalab-dockers#7]
I tried to use the docker image codalab/codalab-legacy:py37 while holding a competition. However, all test submissions I tried only reflected the submitted status rather than finished. Is there any issue with the docker image?
![微信图片_20230904213018](https://github.com/codalab/codalab-dockers/assets/142861685/d406fb2b-1775-4941-a511-a771eec7df80)

**Comment by Didayolo** [comment]
Hello,

I think that the docker image is fine. 

- Which queue are you using? The default or a custom queue?
- What is the URL of your competition?
- Did the submissions work in the past?

**Comment by BrainTeaserSem** [comment]
Hi,

Sorry for the late reply. The issues were solved, which I think is related to the internet issue.
