### ISSUE TITLE
WARNING: The NVIDIA Driver was not detected.

### ISSUE THREAD

**Issue by kwang2049** [codalab/codalab-dockers#9]
I specified codalab/codalab-legacy:gpu310 as the Competition Docker Image for a competition hosted at https://www.codabench.org/. However, there are two issues:

1. > WARNING: The NVIDIA Driver was not detected.

Is GPU available in the codabench server?

Warning message below:

```bash
==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .
```

2. It is really slow for each submission (>10min). Does it try to pull the image all over again for each submission?

Thanks for your help.

**Comment by Didayolo** [comment]
Hi @kwang2049,

Is your competition using the default job queue? To know, go to the editor and see if something is set in the "queue" field.
The field is probably empty if you did not set anything.

The default queue is a set of CPU compute workers provided by the platform. If you want to use GPU workers, you'll have to provide your own workers. To do so, you need to create a queue and link the workers to it.

See: 
- https://github.com/codalab/codabench/wiki/Queue-Management
- https://github.com/codalab/codabench/wiki/Compute-Worker-Management---Setup

**Comment by kwang2049** [comment]
I see. We did not set this GPU worker thing. Thanks for your quick reply!
